### ISSUE TITLE
Newly created app missing Bootstrap.groovy file

### ISSUE THREAD

**Issue by puneetbehl** [grails/grails-forge#186]
### Description

A fresh Grails 6 application is missing the BootStrap.groovy file.

### Steps to Reproduce

1. Goto https://start.grails.org/
2. Click on the "Generate Project" button and Download the Zip.
3. Open the Project in your favorite IDE or Text Editor
4. Notice the file `grails-app/init/com/example/Bootstrap.groovy` is missing.

**Comment by matrei** [comment]
Fixed by #204
