### ISSUE TITLE
Assets from plugin are not packaged by default, need to add packagePlugin = true in build.gradle file

### ISSUE THREAD

**Issue by jebabarit** [grails/grails-forge#197]
### Description

Assets from plugin are not packaged by default, need to add packagePlugin = true in build.gradle file

### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

Using grails cli 
1. Create a web-plugin
2. Add a asset in web-plugin :  web-plugin/grails/assets/images/example.svg
3. Add a asset in web-app :      web-app/grails/assets/images/example-2.svg
4. Run app :

### Expected Behaviour

Both assets should be found

### Actual Behaviour

the asset from the plugin : localhost:8080/assets/example.svg is found 
but :
the asset from the app : localhost:8080/assets/example-2.svg is not found 

unless : 
assets {
    ...
    packagePlugin = true
    ...
}
is added to the buld.gradle of the plugin

### Environment Information

- **Operating System**: ubuntu
- **Grails Version:** 6
- **JDK Version:** 11

### Example Application

- TODO: Sorry can't push to github at work at the moment

**Comment by ianroberts** [comment]
https://start.grails.org still generates plugins without `packagePlugin = true` in the `build.gradle` - when will this fix go live on there?

**Comment by puneetbehl** [comment]
This is will be resolved with Grails 6.1.0 or you can test with 6.1.0-SNAPSHOT.
