### ISSUE TITLE
The Selenium version is unnecessarily declared multiple times

### ISSUE THREAD

**Issue by matrei** [grails/grails-forge#227]
### Description

The selenium version is unnecessarily duplicated in the dependencies section, even though it is explicitly declared in the configurations section.

### Steps to Reproduce

1. Create a new Grails 6.1.0 app with `grails create-app g610app`
2. Open `build.gradle`

### Expected Behaviour

The selenium version only needs to be declared in the configurations block.

### Actual Behaviour

The selenium version is also declared 6 times in the dependencies block.

**Comment by jamesfredley** [comment]
I believe this is address for 7.0.x.

**Comment by matrei** [comment]
Fixed in Grails 7
