### ISSUE TITLE
In the application.yml file the 'info app' settings are not loaded correctly.

### ISSUE THREAD

**Issue by fernando88to** [grails/grails-forge#262]
### Description

In the application.yml file the 'info app' settings are not loaded correctly.

### Steps to Reproduce

1. Create an application

### Expected Behaviour

In the application.yml file the information below is not being loaded

```
info:
  app:
    name: grails6_1_0
    version: '0.1'
    grailsVersion: 6.1.0
```

### Actual Behaviour

In the application.yml file the information below should be loaded.

```
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
```

### Environment Information

- **Operating System**: Manjaro
- **Grails Version:** 6.1.0
- **JDK Version:** Temurin-11.0.21+9

**Comment by matrei** [comment]
This was resolved by #232 and applied in 6.1.1
