### ISSUE TITLE
The latest build is failing

### ISSUE THREAD

**Issue by puneetbehl** [grails/grails-forge#294]
Hi @matrei  it seems the latest build is failing after merging your changes. Something might be different between the Java CI workflow execution on PR vs Push. 

I took a quick look on the failure, and it seems the tests need to be update to reflect the newer version of dependencies. Could you please take a deeper look and send a PR to fix the build. 

Also, at some point we would need to make sure that build executed on push should not fail when the PR is successful.

**Comment by matrei** [comment]
@puneetbehl It was when you merged #282 that the build started failing.
The tests fail because renovate does not update the version values in the tests.

In my latest PR #285, I have fixed this.
