### ISSUE TITLE
6.2.0: grails create-app references grails-gradle-plugin 6.1.2

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-forge#337]
```
sdk use grails 6.2.0
grails create-app website
```

results in:

[buildSrc/build.gradle](https://github.com/codeconsole/website/blob/6.2.0/buildSrc/build.gradle#L7)
```gradle
repositories {
    mavenLocal()
    mavenCentral()
    maven { url "https://repo.grails.org/grails/core/" }
}
dependencies {
    implementation("com.bertramlabs.plugins:asset-pipeline-gradle:4.4.0")
    implementation("org.grails:grails-gradle-plugin:6.1.2")
    implementation("org.grails.plugins:hibernate5:8.1.0")
}
```

**Comment by puneetbehl** [comment]
Thank you, I'm aware of the problem. Updating to Grails Gradle Plugin 6.2.0 breaks some functionality around the scaffolding plugin. We are investigating the problem and will soon do a patch release 6.2.1 with it.

**Comment by jamesfredley** [comment]
Grails 6.2.1 will use org.grails:grails-gradle-plugin:6.2.1
