### ISSUE TITLE
Determine what adds the next snapshot to https://start.grails.org/

### ISSUE THREAD

**Issue by jamesfredley** [grails/grails-forge#377]
https://github.com/grails/grails-forge/actions/runs/11172670058 didn't seem to do it.

**Comment by jamesfredley** [comment]
@puneetbehl @osscontributor we could not figure this out.

**Comment by matrei** [comment]
Looking at the history, maybe it is this this kind of change that does it? (setting `grailsVersion=6.2.2-SNAPSHOT`)
https://github.com/grails/grails-forge/commit/3edf55e78c6fe2378a6808f0ce647c78ce28539a

**Comment by jamesfredley** [comment]
Attempt #2:  https://github.com/grails/grails-forge/pull/379
