### ISSUE TITLE
Remove buildSrc and settings.gradle files by default, change to optional features

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-forge#406]
buildSrc overcomplicates the build and makes upgrading more difficult.

A lot of people reference the results of create-app in determining how to upgrade their existing app.  People are finding the new configuration challenging.  

`buildSrc/` and `settings.gradle` can be completely eliminated by simply adding the builscript at the top of build.gradle

```gradle
buildscript {
    repositories {
        maven { url "https://repo.grails.org/grails/core/" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:6.2.1"
    }
}

plugins {
    id "groovy"
    id "com.github.erdi.webdriver-binaries" version "3.2"
    id "war"
    id "idea"
    id "com.bertramlabs.asset-pipeline" version "4.5.1"
    id "application"
    id "eclipse"
}
apply plugin:"org.grails.grails-web"
apply plugin:"org.grails.grails-gsp"
```

This should go out in 6.2.2 unless we plan on continuing support for 5.x

**Comment by codeconsole** [comment]
https://github.com/grails/grails-forge/blob/a6860bacaa901dac54f67b5e5319d5beaaf95244/grails-forge-core/src/main/java/org/grails/forge/feature/build/gradle/Gradle.java#L77-L82

https://github.com/grails/grails-forge/blob/a6860bacaa901dac54f67b5e5319d5beaaf95244/grails-forge-core/src/main/java/org/grails/forge/feature/database/HibernateGorm.java#L82-L85

@jamesfredley started removal in 7
https://github.com/grails/grails-forge/commit/514e2e7886005248d3695e96e9d4f666ccdaa3f9

but removal must also be done in
HibernateGorm, AssetPipeline, GrailsGradlePlugin, DatabaseMigrationPlugin, ViewJson, ViewMarkup

**Comment by matrei** [comment]
Is this really something we want to change in a patch release? Isn't it better to just fix the bugs and move on?

**Comment by codeconsole** [comment]
> Is this really something we want to change in a patch release? Isn't it better to just fix the bugs and move on?

1. The fix is already needed in 7.  Why not update both?  If the work wasn't already needed for 7, I would say hold off, but isn't it easy to apply the same fix in both places?
2. Keeping it will cause confusion for anyone that upgrades to 6 between now and when 7 is finally released.   6 is the only version that uses this technique.  I would imagine there are more people still using version < 6 then that are using 6 and a lot of upgrades could happen between versions.

**Comment by matrei** [comment]
I still think it's a bad idea to start changing things in what could be the last patch release of Grails 6. There will on doubt be repercussions. Also the documentation for Grails 6 has to be updated.

**Comment by codeconsole** [comment]
@matrei do the docs explain why versions are listed multiple times and the actual reason for `buildSrc`?

We aren't changing anything related to 6.2.x   We would just be changing grails-forge which already is generating bad configurations.   The configuration I am recommending works and is easy to understand. 

If you are strongly opposed, I will defer the decision to you, but it would be nice if this was fixed.

Also, I do highly recommend 1 change.  `skipDigests = true` should be added to the assets block {} as this is [not default behavior](https://github.com/bertramdev/asset-pipeline/commit/186b7bee2ae092aad88ecd6f19b45a0109e179cc) in asset pipeline 4.x and results in a massive build bootJar/bootWar.

I should also mention that if you use grails-shell to create a 6.2.1 app, it does not produce a buildSrc directory. This is forge specific and very contradictory to everything else.

**Comment by matrei** [comment]
> the actual reason for buildSrc?

https://docs.grails.org/6.2.1/guide/single.html#_6_3_grails_adoption_of_buildsrc_folder_for_buildscript_dependencies

> We aren't changing anything related to 6.2.x

We should approach a Grails release as a unified whole, considering all its components together.

> Also, I do highly recommend 1 change. skipDigests = true

If this is a bug, it should be fixed in 6.2.2.

> I should also mention that if you use grails-shell to create a 6.2.1 app, it does not produce a buildSrc directory. This is forge specific and very contradictory to everything else.

Yes, this is unfortunate, but the expected behavior of Grails 6.2 is to create a buildSrc directory.

> Keeping it will cause confusion for anyone that upgrades to 6 between now and when 7 is finally released

Removing it will also cause confusion.

> If you are strongly opposed, I will defer the decision to you, but it would be nice if this was fixed.

I just don't see any strong reasons to change this in a patch release.

**Comment by jamesfredley** [comment]
I am going to move this ticket to Grails 7, but also create another issue to consolidate the Gradle plugins, to one location, for Grails 6.2.2, without removing any files or directories.  I believe that is the solution which meets in the middle of the debate.  

For Grails 7, I plan to make `buildSrc` and `settings.gradle` optional features, so they are not there by default but are selectable when desired.  Gradle plugins should be defined in one location, if the optional features are selected.   `buildSrc` can be replaced with `buildscript{}`, `plugins{}` and `apply plugin` in the main `build.gradle`.  Unfortunately, there are certain things that can only live in `settings.gradle`, including Gradle Settings Plugins (https://github.com/gradle/foojay-toolchains).  

`skipDigests = true` should be handled in another issue.

**Comment by jamesfredley** [comment]
https://github.com/grails/grails-forge/issues/408

**Comment by jamesfredley** [comment]
https://github.com/grails/grails-forge/issues/409

**Comment by codeconsole** [comment]
> I am going to move this ticket to Grails 7, but also create another issue to consolidate the Gradle plugins, to one location, for Grails 6.2.2, without removing any files or directories. I believe that is the solution which meets in the middle of the debate.
> 
> For Grails 7, I plan to make `buildSrc` and `settings.gradle` optional features, so they are not there by default but are selectable when desired. Gradle plugins should be defined in one location, if the optional features are selected. `buildSrc` can be replaced with `buildscript{}`, `plugins{}` and `apply plugin` in the main `build.gradle`. Unfortunately, there are certain things that can only live in `settings.gradle`, including Gradle Settings Plugins (https://github.com/gradle/foojay-toolchains).
> 
> `skipDigests = true` should be handled in another issue.

@jamesfredley buildscriot {} will not be required in Grails 7.  @davydotcom said it’s easy to publish to cradle plugin repo

**Comment by jamesfredley** [comment]
I agree by default and for most applications.  We will need to publish several Gradle plugins to get there, starting with these:

```
org.grails:grails-gradle-plugin - with all the subproject plugins
org.grails.plugins:hibernate5
org.grails.plugins:database-migration
org.grails:grails-shell
```
plus others run by `grails-shell` or `./gradle runCommand`

Users with custom Gradle commands or plugins not published to Gradle's plugin portal will likely still use buildscript {} or buildSrc to apply them, but that does not need to be included in default generated apps.
