### ISSUE TITLE
Grails 6.2.2: Consolidate Gradle Plugin config to one location

### ISSUE THREAD

**Issue by jamesfredley** [grails/grails-forge#408]
Currently in 3 locations, `buildSrc/build.gradle`, `settings.gradle` and `build.gradle`.

**Comment by matrei** [comment]
@jamesfredley Are we ready to close this issue as not planned, as it was moved to the Grails 7 board?

**Comment by codeconsole** [comment]
@matrei I've been thinking about this one more and I really think we should push this into Grails 6.2.2

It's a very simple change and we are only talking about modifying forge`create-app`
This requires no changes other than to forge. 

The reason for this change is that it seems that most Grails users are on 5.x or less. If we are not going to support 5.x and force them to upgrade to 6.x prior to the release of 7.x, it is going to upset a lot of people and make the 7.x upgrade more difficult for them.

**Comment by codeconsole** [comment]
This is a very simple task.

All that needs to be done is delete `buildSrc/build.gradle`, `settings.gradle` and stick this to the top of `build.gradle`

```gradle
buildscript {
    repositories {
        maven { url "https://repo.grails.org/grails/core/" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:6.2.1"
    }
}

plugins {
    id "groovy"
    id "com.github.erdi.webdriver-binaries" version "3.2"
    id "war"
    id "idea"
    id "com.bertramlabs.asset-pipeline" version "4.5.1"
    id "application"
    id "eclipse"
}
apply plugin:"org.grails.grails-web"
apply plugin:"org.grails.grails-gsp"
```

**Comment by matrei** [comment]
> The reason for this change is that it seems that most Grails users are on 5.x or less. If we are not going to support 5.x and force them to upgrade to 6.x prior to the release of 7.x, it is going to upset a lot of people and make the 7.x upgrade more difficult for them.

Is there any reason to go through 6 to get to 7?

**Comment by codeconsole** [comment]
@jamesfredley said on Thursday he would get it done this week and then we can release 6.2.2

The reason to get it done in 6 is for anyone that upgrades to 6 before 7 is released.

**Comment by jamesfredley** [comment]
I am going to try to have a PR ready by the end of today and then we can continue the conversation against those code changes.

**Comment by jamesfredley** [comment]
https://github.com/grails/grails-gradle-plugin/issues/351
