### ISSUE TITLE
Grails 6.2.2 support for macOS ARM on sdkman

### ISSUE THREAD

**Issue by jamesfredley** [grails/grails-forge#439]
Java 11 and Graalvm do not support macOS ARM.  When we did the 6.2.2 release:  https://github.com/grails/grails-forge/actions/runs/11942648932, we published the macOS Intel native binary to SDKman, but not the macOS Arm native binary.  

Is there a way for SDKman to provide the macOS Intel native binary for macOS Arm machines since Rosetta should be able to convert and run it?

This will not be an issue on Grails 7, since it will be Java 17 min and Graalvm will support macOS Arm.

**Comment by jeffscottbrown** [comment]
> When we did the 6.2.2 release: https://github.com/grails/grails-forge/actions/runs/11942648932, we published the macOS Intel native binary to SDKman, but not the macOS Arm native binary.

Is this what you expect to see?

```
% file `which grails`
/Users/brownj/.sdkman/candidates/grails/6.2.2/bin/grails: Mach-O 64-bit executable arm64
```

**Comment by jdaugherty** [comment]
https://github.com/grails/grails-forge/pull/434 fixed this in the 6.2.x branch already

**Comment by jdaugherty** [comment]
We just need to merge to 7.0.x.

**Comment by jamesfredley** [comment]
I was out of the loop and this was already resolved.
